name: bag_tracking
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  flutter_svg: ^2.0.17
  pin_code_fields: ^8.0.1
  geolocator: ^13.0.2
  flutter_map: ^8.1.1
  url_launcher: ^6.1.14
  sliding_up_panel: ^2.0.0+1
  latlong2: ^0.9.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  # shared_preferences: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true    
  assets:
    - assets/imgs/
    - assets/Icons/



